### PR TITLE
Latest Working Rlease of Real Time Cadmium

### PR DESCRIPTION
**Pull request by BenEarle**
Hi, 
Cristina asked that we make a branch for the development of Real Time Cadmium. RT-Cadmium works on M-Bed enabled ARM boards and standard Linux. It includes a library of simple port drivers, support for asynchronous events (interrupts, etc.), and a basic RT scheduler. 

It is functional, however I do think that some of the implementations can be improved and I plan to continue working on it. If you have any questions or comments please feel free to let me know!

### CODE REVIEW

**Comment by BenEarle** [comment]
Would it be easier to review if I collapsed all of our changes into one big commit?

**Comment by sdavtaker** [comment]
Not really. Multiple commits are fine. Thanks for sharing.

**Comment by cruizm** [comment]
Hello @gtrabes @romancardenas @sdavtaker,
We need to merge RT-Cadmium in the repository as more and more people are using it and we need a unified version to be provided. 
Can you please check that you are ok with the pull request?

**Comment by jonmenard** [comment]
I have been manually testing this version against the current master version of SimulationEverywhere/Cadmium. The only this I have found that doesn't work is when testing older not RT models, they require a file called "cadmium/basic_model/pdevs/iestream.hpp". However, when I move this file over I can run the older models without any errors. I also checked the simulation results for ABP and Asset Price Simulator and compared them directly side by side. They produce the exact same results. Given this, I believe the branch can be merged without breaking the other branch.

I should note though, this branch is not being compared to Master but instead RT_DEVS_Devlopement which is 60 branched behind master

**Comment by jonmenard** [comment]
I have permission to merge this request. Note we are missing iestream.hpp. I will add this file after, since I do not have permission to upload to Kyle's branch

**Pull request merged**
